# Tell Nixpacks this is a Node.js project
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "npm start"
