# Tell Nixpacks this is a Node.js project in server directory
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd server && npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "cd server && npm start"
